### ISSUE TITLE
Queue Trimming/TTL

### ISSUE THREAD

**Issue by davidpadbury** [QubitProducts/queue-that#10]
If my process function continuously fails (e.g. server I'm posting to is down/blocked) I'll slowly build up a large number of items which will never empty. I imagine if this grows large the persistence in local-storage with JSON parsing and stringify in and out could become expensive.

Any interest in accepting a feature for throwing away the items in the queue (likely after a certain time) regardless of whether they were processed or not?

**Comment by roberttod** [comment]
I actually spent a few hours laying awake a couple of weeks ago thinking about this problem, I was also worried it might exceed the maximum localStorage size.

I would like to find out roughly the maximum number of characters or tasks that could be parsed before any supported browser takes > 50ms and then use that as a maximum, throwing away the oldest tasks only when this limit is exceeded (so the throwing away would only happen when you queue new tasks). I would expect that to be the default for an option passed to `queueThat`.

Would that work for you?

**Comment by davidpadbury** [comment]
Could just do a function to prune the list before adding new items? For what I'm doing I could have a more aggressive eviction strategy. If things are getting really stale (e.g. 24hr+) they can just be thrown away. 

Doing things on JSON size would be hard to do precisely, but a crude approach would probably be fine for most cases (JSONified length gets beyond xK length we throw out a couple of items for every item you add).

**Comment by roberttod** [comment]
I would rather not do an expire time
- You need to store a timestamp for each task, adding to the parse time
- There is a bit more logic needed for implementation
- If the queue grows quickly for whatever reason, it may still get too large

I like the idea of throwing away a couple of items for each added item once the length is too long, I think that will work well.

**Comment by davidpadbury** [comment]
Yeah - fair enough, that wouldn't work generally. So we work out a reasonable length limit then start throwing away a couple. Will work on in the next week or so.

**Comment by roberttod** [comment]
Sounds good.

**Comment by davidpadbury** [comment]
:tada:
