### ISSUE TITLE
Quota Exceeded Error

### ISSUE THREAD

**Issue by roberttod** [QubitProducts/queue-that#12]
In incognito Safari there is a `Quota Exceeded Error` that stops the queue from working.

**Comment by roberttod** [comment]
https://msdn.microsoft.com/library/cc197016(v=vs.85).aspx

**Comment by davidpadbury** [comment]
I think we could have different approaches to deal with `localStorage` never working (Incognito Safari), vs a working queue but being conservative with how much space we're using.

To deal with it never working, on load `queue-that` immediately tries to write something tiny to `localStorage` just to see if it works at all. If it fails we give up on `localStorage` entirely, and when queuing requests are made it just immediately invokes `process` (or perhaps debounce a brief period to somewhat match current behavior).

For being conservative, we could optionally supply a pruning callback on queue creation which would receive all currently queued items and return some (ideally smaller) subset of them. This would allow us to prioritise what is kept and what is thrown away. If we know quotas, we invoke it when we can tell that  `localStorage` space is running out. Alternatively, if we can't tell what capacity `localStorage` has, perhaps a dumb when length greater than X, localStorage sets no longer working, or on a process call failure.

**Comment by matt-ball** [comment]
https://app.asana.com/0/12572779201863/146994200655076
