### ISSUE TITLE
Stop polling

### ISSUE THREAD

**Issue by roberttod** [QubitProducts/queue-that#22]
There is one active tab that polls for any changes in the queue and sends the queue when it is a stable length > 0 for two polling loops. Instead, every time an event is added, wait n ms to check the queue is a stable length and then send the data.

**Advantages**
- Get rid of dirty dirty polling
- Flexibility to reduce debounce window without worrying about performance

**Disadvantages**
- If there are 2 or more tabs open and one of the tabs is closed while events are being sent, the other tabs would no longer send those events until a new event occurred in one of those tabs
  - Could mitigate this by long polling
  - I doubt this would account for any detectable data loss

**Comment by rdecoene** [comment]
This one's done right?
