### ISSUE TITLE
Expose whether an event has been sent

### ISSUE THREAD

**Issue by roberttod** [QubitProducts/queue-that#25]
I need to be able to detect whether a batch that is being sent may contain events that have already been sent before. We can do this a few ways.

**Wrap events with meta data in localStorage**
When events are stored they will be stored along with their send count and any other meta data that could be potentially added down the line.

❤️ Allows for many more features

❤️ Pretty simple to implement

😟 Need to iterate over all events to check for events being resent

😟 Is not backwards compatible

😟 Need to think of migrating local storage queues (could just delete old ones, wouldn't lose much data at all)

**Keep a hash in localStorage keyed by item ID**
Keep a hash in `localStorage` with info related to each event, `queueThat.getEventsInfo` will parse and return the hash.

❤️ Is backwards compatible

❤️ Does not need a migration

😟 Items need an ID in order to be hashed

😟 Uses another `localStorage` key

😟 Not trivial to implement, need to maintain the hash

😟 Still need to iterate over all events to check they have been sent

**Reprocess method**
Keep two event queues. Call the `process` callback when events are ready to go to the server, if a `reprocess` callback is provided then call that for events that have already gone to the server.

❤️ Most efficient solution computationally

❤️ Gives a greater degree of control, `process` is not called with events that have been sent before (if `reprocess` exists)

❤️ Backwards compatible

❤️ No migration needed

😟 Probably much more work - including many tests

😟 Uses another `localStorage` key

**Comment by roberttod** [comment]
@davidpadbury read through these if you could. After writing them, I am kind of inclined to do the third option, a reprocess option.

**Comment by davidpadbury** [comment]
So these events will be ones that we know we have made a request to send, but did not receive a response?

**Comment by roberttod** [comment]
Yes, sort of. An event will be labeled as processed immediately (and synchronously) after process is called. The event will be removed from the queue if process succeeds. If the page is closed or process responds with an error then the event will be left labeled as processed.

**Comment by roberttod** [comment]
So I will instead go with a counter to specify the number of items that are being processed. The process function will be passed a third `meta` argument with this info.

❤️ Backwards compatible

❤️ Doesn't need a migration

❤️ Computationally cheap

❤️ Easy to implement

😟 Requires the queue to be read in a specific order

😟 Becomes more difficult if paralel batches are considered

😟 Makes an odd process function, with the callback as the second of 3 options (unless we decide to not be backwards compatible)

Thanks to @davidpadbury for this solution.
